modLoader="javafml"
loaderVersion="[36,)"
license="Apache 2.0"

[[mods]]
modId="adiectamateria"
version="2.4.2"
displayName="AdiectaMateria"
displayURL="https://github.com/CleverNucleus/AdiectaMateria"
logoFile="logo.png"
credits="CleverNucleus: Code & major texturer; Joe Williamson: Grafter, Arrow head & Plant Fibre textures; Orteil: Soul texture."
authors="CleverNucleus"

description='''
A stepping stone vanilla+ mod.
'''

[[dependencies.adiectamateria]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.adiectamateria]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"