modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="adiectamateria"
version="2.3.2"
displayName="AdiectaMateria"
displayURL="https://github.com/CleverNucleus/AdiectaMateria"
logoFile="logo.png"
credits="CleverNucleus"
authors="CleverNucleus"

description='''
MetalSmith. In dev.
'''

[[dependencies.adiectamateria]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.adiectamateria]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"