modLoader="javafml"
loaderVersion="[33,)"
license="Apache License 2.0"

[[mods]]
modId="adiectamateria"
version="2.3.4"
displayName="AdiectaMateria"
displayURL="https://github.com/CleverNucleus/AdiectaMateria"
logoFile="logo.png"
credits="CleverNucleus"
authors="CleverNucleus"

description='''
Stepping stone utility mod; lets the player make things differently.
'''

[[dependencies.adiectamateria]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.adiectamateria]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
